### PR TITLE
Adding Test2.java file

### PR DESCRIPTION
**Pull request by ionicsagar2909**
Hi ,

I have committed Test2.java.
Please review and approve.

Regards
ionicsagar2909

### CODE REVIEW

**Comment by ionicsagar2909** [comment]
Hi X , 

Your code looks good , please add one more check.
Regards
Lead

**Comment by sagarkaushal** [comment]
Hi X,

Looks good.
Please add smthing

**Comment by ionicsagar2909** [comment]
Hi Code changes.

Regards 
X

**Comment by sagarkaushal** [comment]
Hi X, 
Your code looks good.
Please merge

**Pull request merged**
